IF OBJECT_ID ('bronze.operational_delays_haul','U') IS NOT NULL
	DROP TABLE bronze.operational_delays_haul;
CREATE TABLE bronze.operational_delays_haul (
	AssetDescription NVARCHAR (50),
	StartTimestamp DATETIME,
	EndTimestamp DATETIME,
	ReportEventStartTimestamp DATETIME,
	ReportEventEndTimestamp DATETIME,
	MineAreaId NVARCHAR(50),
	MineAreaCaption VARCHAR(25),
	AssetGroup VARCHAR(25),
	AssetClass VARCHAR(25),
	DurationSeconds INT,
	EventType NVARCHAR(50),
	OriginalEventType NVARCHAR(50),
	AnnotationStartTimestamp NVARCHAR(50),
	AnnotationEndTimestamp NVARCHAR(50),
	Category NVARCHAR(50),
	Reason NVARCHAR(50),
	description_haul NVARCHAR(50),
	Code NVARCHAR(50),
	AnnotationType NVARCHAR(50),
	GeofenceName NVARCHAR(50),
	GeofenceType NVARCHAR(50),
	work_shift NVARCHAR(50),
	MasterEventType NVARCHAR(50),
	planned_maintenance NVARCHAR(10)
	)
;
IF OBJECT_ID ('bronze.cycle_review','U') IS NOT NULL
	DROP TABLE bronze.cycle_review;

;
 CREATE TABLE  bronze.cycle_review (
	start_timestamp NVARCHAR (50),
	truck NVARCHAR(50),
	shovel NVARCHAR(50),
	material NVARCHAR (50),
	loading_area NVARCHAR (50),
	dumping_area NVARCHAR (50),
	tonnage NVARCHAR (50),
	fill_time NVARCHAR (50),
	queue_time NVARCHAR (50),
	cycle_time NVARCHAR (50),
	travel_distance_laden_metres NVARCHAR (50),
	average_speed_laden_km_h FLOAT,
	travel_seconds_laden NVARCHAR (50),
	travel_distance_unladen_metres NVARCHAR (50),
	average_speed_unladen_km_h FLOAT,
	travel_seconds_unladen NVARCHAR (50),
	dumping_time NVARCHAR (50),
	loading_time NVARCHAR (50),
	dumping_timestamp NVARCHAR (50),
	loading_timestamp NVARCHAR (50),
	cycle_time_seconds NVARCHAR (50)
	

;
IF OBJECT_ID ('bronze.multi_shift','U') IS NOT NULL
	DROP TABLE bronze.multi_shift;

;
CREATE TABLE bronze.multi_shift (
shift_caption NVARCHAR(50),
shift_date DATETIME,
day_of_month INT,
asset_caption NVARCHAR(50),
asset_class NVARCHAR(50),
ignition_hour_start FLOAT,
ignition_hour_end FLOAT,
total_ingintion_hour FLOAT,
first_ignition_on DATETIME,
last_ignition_off DATETIME,
cycle_count INT,
average_cycle_distance_laden FLOAT,
first_cycle_start_timestamp DATETIME,
last_cycle_start_timestamp DATETIME,
BCM_Total FLOAT,
tonnage_total INT,
assest_group_caption NVARCHAR(50),
maintenance_hours FLOAT,
planned_maintenance_hours FLOAT,
uncontrollable_hours  FLOAT,
total_idling_hours FLOAT,
availability_ INT,
utilization_seconds  INT,
cycle_delay_seconds INT,
known_operation_delay_seconds INT,
other_travel_seconds INT,
Unknown_operation_dealy_seconds INT

)
;
IF OBJECT_ID ('bronze.maintenance','U') IS NOT NULL
	DROP TABLE bronze.maintenance;
CREATE TABLE bronze.maintenance ( 
	assetDescription NVARCHAR(50),
	ActualEventStartTimestamp DATETIME,
	ActualEventEndTimestamp DATETIME,
	MaintenanceAreaName NVARCHAR(50),
	JobStartTimestamp DATETIME,
	JobCompletedTimestamp DATETIME,
	AssetCollectedTimestamp DATETIME,
	MaintenanceArtisanName NVARCHAR(50),
	MaintenanceReason NVARCHAR(50),
	Remarks NVARCHAR(50),
	IsAutoGenerated NVARCHAR(50),
	IsPlanned NVARCHAR(50),
	AutoStartTimestamp DATETIME,
	AutoEndTimestamp DATETIME,
	AutoGeofence NVARCHAR(50),
	Reason NVARCHAR(50),
	Category NVARCHAR(50),
	AssetGroup NVARCHAR(50),
	ReportEventStartTimestamp DATETIME,
	ReportEventEndTimestamp DATETIME,
	AssetId NVARCHAR(50),
	OperatorTagId NVARCHAR(50),
	Operator_ClientCode  NVARCHAR(50),
	Operator_KnownAs NVARCHAR(50),
	Duration_in_hours INT,
	Production_day INT

);
