
DROP TABLE IF EXISTS bronze.operational_delays_haul;

CREATE TABLE bronze.operational_delays_haul (
	AssetDescription NVARCHAR (50),
	StartTimestamp NVARCHAR (50),
	EndTimestamp NVARCHAR (50),
	ReportEventStartTimestamp NVARCHAR (50),
	ReportEventEndTimestamp NVARCHAR (50),
	MineAreaId NVARCHAR(50),
	MineAreaCaption VARCHAR(25),
	AssetGroup VARCHAR(25),
	AssetClass VARCHAR(25),
	DurationSeconds NVARCHAR(50),
	EventType NVARCHAR(50),
	OriginalEventType NVARCHAR(50),
	AnnotationStartTimestamp NVARCHAR(50),
	AnnotationEndTimestamp NVARCHAR(50),
	Category NVARCHAR(50),
	Reason NVARCHAR(50),
	description_haul NVARCHAR(250),
	Code NVARCHAR(50),
	AnnotationType NVARCHAR(50),
	GeofenceName NVARCHAR(50),
	GeofenceType NVARCHAR(50),
	work_shift NVARCHAR(50),
	MasterEventType NVARCHAR(50),
	planned_maintenance NVARCHAR(10)
	)
;
DROP TABLE IF EXISTS bronze.cycle_review;

;
 CREATE TABLE  bronze.cycle_review (
	start_timestamp NVARCHAR (50),
	truck NVARCHAR(50),
	shovel NVARCHAR(50),
	material NVARCHAR (50),
	loading_area NVARCHAR (50),
	dumping_area NVARCHAR (50),
	tonnage NVARCHAR (50),
	fill_time NVARCHAR (50),
	queue_time NVARCHAR (50),
	cycle_time NVARCHAR (50),
	travel_distance_laden_metres NVARCHAR (50),
	average_speed_laden_km_h FLOAT,
	travel_seconds_laden NVARCHAR (50),
	travel_distance_unladen_metres NVARCHAR (50),
	average_speed_unladen_km_h FLOAT,
	travel_seconds_unladen NVARCHAR (50),
	dumping_time NVARCHAR (50),
	loading_time NVARCHAR (50),
	dumping_timestamp NVARCHAR (50),
	loading_timestamp NVARCHAR (50),
	cycle_time_seconds NVARCHAR (50)
	

;
DROP TABLE IF EXISTS bronze.multi_shift
;
CREATE TABLE bronze.multi_shift (
shift_caption NVARCHAR(50),
shift_date NVARCHAR(50),
day_of_month NVARCHAR(50),
asset_caption NVARCHAR(50),
asset_class NVARCHAR(50),
ignition_hour_start NVARCHAR(50),
ignition_hour_end NVARCHAR(50),
total_ingintion_hour NVARCHAR(50),
first_ignition_on NVARCHAR(50),
last_ignition_off NVARCHAR(50),
cycle_count NVARCHAR(50),
average_cycle_distance_laden NVARCHAR(50),
first_cycle_start_timestamp NVARCHAR(50),
last_cycle_start_timestamp NVARCHAR(50),
BCM_Total NVARCHAR(50),
tonnage_total NVARCHAR(50),
assest_group_caption NVARCHAR(50),
maintenance_hours NVARCHAR(50),
planned_maintenance_hours NVARCHAR(50),
uncontrollable_hours  NVARCHAR(50),
total_idling_hours NVARCHAR(50),
availability_ NVARCHAR(50),
utilization_seconds  NVARCHAR(50),
cycle_delay_seconds NVARCHAR(50),
known_operation_delay_seconds NVARCHAR(50),
other_travel_seconds NVARCHAR(50),
Unknown_operation_dealy_seconds NVARCHAR(50)
)
;
DROP TABLE IF EXISTS bronze.maintenance;
CREATE TABLE bronze.maintenance ( 
	assetDescription NVARCHAR(50),
	ActualEventStartTimestamp NVARCHAR(50),
	ActualEventEndTimestamp NVARCHAR(50),
	MaintenanceAreaName NVARCHAR(50),
	JobStartTimestamp NVARCHAR(50),
	JobCompletedTimestamp NVARCHAR(50),
	AssetCollectedTimestamp NVARCHAR(50),
	MaintenanceArtisanName NVARCHAR(50),
	MaintenanceReason NVARCHAR(500),
	Remarks NVARCHAR(500),
	IsAutoGenerated NVARCHAR(50),
	IsPlanned NVARCHAR(50),
	AutoStartTimestamp NVARCHAR(50),
	AutoEndTimestamp NVARCHAR(50),
	AutoGeofence NVARCHAR(50),
	Reason NVARCHAR(50),
	Category NVARCHAR(50),
	AssetGroup NVARCHAR(50),
	ReportEventStartTimestamp NVARCHAR(50),
	ReportEventEndTimestamp NVARCHAR(50),
	AssetId NVARCHAR(50),
	OperatorTagId NVARCHAR(50),
	Operator_ClientCode  NVARCHAR(50),
	Operator_KnownAs NVARCHAR(50),
	Duration_in_hours NVARCHAR(50),
	Production_day NVARCHAR(50)
)
