
DROP TABLE IF EXISTS silver.operational_delays_haul;
go
CREATE TABLE silver.operational_delays_haul (
	AssetDescription NVARCHAR (50),
	StartTimestamp DATETIME,
	EndTimestamp DATETIME ,
	ReportEventStartTimestamp DATETIME,
	ReportEventEndTimestamp DATETIME,
	MineAreaId NVARCHAR(50),
	MineAreaCaption VARCHAR(25),
	AssetGroup VARCHAR(25),
	AssetClass VARCHAR(25),
	DurationSeconds INT,
	EventType NVARCHAR(50),
	OriginalEventType NVARCHAR(50),
	AnnotationStartTimestamp DATETIME,
	AnnotationEndTimestamp DATETIME,
	Category NVARCHAR(50),
	Reason NVARCHAR(50),
	description_haul NVARCHAR(250),
	Code NVARCHAR(50),
	AnnotationType NVARCHAR(50),
	GeofenceName NVARCHAR(50),
	GeofenceType NVARCHAR(50),
	work_shift NVARCHAR(50),
	MasterEventType NVARCHAR(50),
	planned_maintenance NVARCHAR(10)
	);
go
DROP TABLE IF EXISTS sivler.cycle_review;

;
go
 CREATE TABLE  silver.cycle_review (
	start_timestamp DATETIME,
	truck NVARCHAR(50),
	shovel NVARCHAR(50),
	material NVARCHAR (50),
	loading_area NVARCHAR (50),
	dumping_area NVARCHAR (50),
	tonnage INT,
	fill_time INT,
	queue_time INT,
	cycle_time INT,
	travel_distance_laden_metres INT,
	average_speed_laden_km_h FLOAT,
	travel_seconds_laden INT,
	travel_distance_unladen_metres INT,
	average_speed_unladen_km_h FLOAT,
	travel_seconds_unladen NVARCHAR (50),
	dumping_time INT,
	loading_time INT,
	dumping_timestamp DATETIME,
	loading_timestamp DATETIME,
	cycle_time_seconds INT
	);
	go 
DROP TABLE IF EXISTS silver.multi_shift
;
go
CREATE TABLE silver.multi_shift (
shift_caption NVARCHAR(50),
shift_date DATETIME,
day_of_month NVARCHAR(50),
asset_caption NVARCHAR(50),
asset_class NVARCHAR(50),
ignition_hour_start FLOAT,
ignition_hour_end FLOAT,
total_ingintion_hour FLOAT,
first_ignition_on DATETIME,
last_ignition_off DATETIME,
cycle_count FLOAT,
average_cycle_distance_laden FLOAT,
first_cycle_start_timestamp DATETIME,
last_cycle_start_timestamp DATETIME,
BCM_Total FLOAT,
tonnage_total FLOAT,
assest_group_caption NVARCHAR(50),
maintenance_hours FLOAT,
planned_maintenance_hours INT,
uncontrollable_hours  FLOAT,
total_idling_hours FLOAT,
availability_ FLOAT,
utilization_seconds  FLOAT,
cycle_delay_seconds FLOAT,
known_operation_delay_seconds FLOAT,
other_travel_seconds FLOAT,
Unknown_operation_dealy_seconds FLOAT
)
;
go
DROP TABLE IF EXISTS silver.maintenance ; 
go
CREATE TABLE silver.maintenance ( 
	assetDescription NVARCHAR(50),
	ActualEventStartTimestamp DATETIME,
	ActualEventEndTimestamp DATETIME,
	MaintenanceAreaName NVARCHAR(50),
	JobStartTimestamp DATETIME,
	JobCompletedTimestamp DATETIME,
	AssetCollectedTimestamp DATETIME,
	MaintenanceArtisanName NVARCHAR(50),
	MaintenanceReason NVARCHAR(500),
	Remarks NVARCHAR(500),
	IsAutoGenerated NVARCHAR(25),
	IsPlanned NVARCHAR(25),
	AutoStartTimestamp NVARCHAR(50),
	AutoEndTimestamp NVARCHAR(50),
	AutoGeofence NVARCHAR(50),
	Reason NVARCHAR(50),
	Category NVARCHAR(50),
	AssetGroup NVARCHAR(50),
	ReportEventStartTimestamp DATETIME,
	ReportEventEndTimestamp DATETIME,
	AssetId NVARCHAR(50),
	OperatorTagId NVARCHAR(50),
	Operator_ClientCode  NVARCHAR(50),
	Operator_KnownAs NVARCHAR(50),
	Duration_in_hours FLOAT,
	Production_day NVARCHAR(50)
)
