CREATE OR ALTER PROCEDURE silver.load_silver AS 
BEGIN 
	DECLARE @start_time DATETIME,@end_time DATETIME ;
	DECLARE @batch_start_time DATETIME,@batch_end_time DATETIME;
	BEGIN TRY
	SET @batch_start_time = GETDATE();
		PRINT '===============================================================';
		PRINT 'LOADING SILVER LAYER';
		PRINT '===============================================================';

		PRINT '---------------------------------------------------------------';
		PRINT 'Loading MOVERS Tables';
		PRINT '---------------------------------------------------------------';
	SET @start_time = GETDATE();
	PRINT'>> Truncating Table: silver.operational_delays_haul';
	TRUNCATE TABLE silver.operational_delays_haul;
	Print '>> Inserting Data Into: silver.operational_delays_haul';
INSERT INTO silver.operational_delays_haul (AssetDescription, starttimestamp, EndTimestamp, ReportEventStartTimestamp, 
ReportEventEndTimestamp, MineAreaId, MineAreaCaption, AssetGroup, AssetClass, 
DurationSeconds, eventtype, OriginalEventType, AnnotationStartTimestamp, AnnotationEndTimestamp, 
Category, reason, description_haul, Code, AnnotationType, GeofenceName, work_shift, 
MasterEventType, planned_maintenance)
SELECT DISTINCT
	o.AssetDescription,
	o.starttimestamp,
	o.EndTimestamp,
	o.ReportEventStartTimestamp,
	o.ReportEventEndTimestamp,
	o.MineAreaId,
	o.MineAreaCaption,
	o.AssetGroup,
	o.AssetClass,
	cast(o.DurationSeconds as INT),
	o.eventtype,
	o.OriginalEventType,
	o.AnnotationStartTimestamp,
	o.AnnotationEndTimestamp,
	o.Category,
	o.reason,
	o.description_haul,
	o.Code,
	o.AnnotationType,
	o.GeofenceName,
	o.work_shift,
	o.MasterEventType,
	o.planned_maintenance
FROM bronze.operational_delays_haul o;
SET @end_time = GETDATE();
PRINT '>>Load Duration: '+ CAST(DATEDIFF(SECOND, @start_time,@end_time) as NVARCHAR) + 'seconds';
PRINT '------------------------------------------------------------------------------------';
SET @start_time = GETDATE();
PRINT'>> Truncating Table: silver .maintenance';
TRUNCATE TABLE silver .maintenance;
Print '>> Inserting Data Into: silver .maintenance';

INSERT INTO silver .maintenance( assetDescription, ActualEventStartTimestamp, ActualEventEndTimestamp, MaintenanceAreaName, JobStartTimestamp, 
JobCompletedTimestamp, AssetCollectedTimestamp, MaintenanceArtisanName, MaintenanceReason,
Remarks, IsAutoGenerated, IsPlanned, AutoStartTimestamp, AutoEndTimestamp, AutoGeofence, Reason, Category, AssetGroup, ReportEventStartTimestamp,
ReportEventEndTimestamp, AssetId, OperatorTagId, Operator_ClientCode, Operator_KnownAs, Duration_in_hours, Production_day)
SELECT DISTINCT
m.assetDescription,
m.ActualEventStartTimestamp,
m.ActualEventEndTimestamp,
m.MaintenanceAreaName,
m.JobStartTimestamp,
m.JobCompletedTimestamp,
m.AssetCollectedTimestamp,
m.MaintenanceArtisanName,
m.MaintenanceReason,
m.Remarks,
m.IsAutoGenerated,
m.IsPlanned,
m.AutoStartTimestamp,
m.AutoEndTimestamp,
m.AutoGeofence,
m.Reason,
m.Category,
m.AssetGroup,
m.ReportEventStartTimestamp,
m.ReportEventEndTimestamp,
m.AssetId,
m.OperatorTagId,
m.Operator_ClientCode,
m.Operator_KnownAs,
cast(m.Duration_in_hours as float),
m.Production_day
FROM bronze.maintenance m ;
SET @end_time = GETDATE();
PRINT '>>Load Duration: '+ CAST(DATEDIFF(SECOND, @start_time,@end_time) as NVARCHAR) + 'seconds';
PRINT '------------------------------------------------------------------------------------';

SET @start_time = GETDATE();
PRINT'>> Truncating Table: silver.multi_shift';
TRUNCATE TABLE silver.multi_shift;
Print '>> Inserting Data Into: silver.multi_shift';
INSERT INTO silver.multi_shift( 
shift_caption, shift_date, day_of_month, asset_caption, asset_class, ignition_hour_start, ignition_hour_end, total_ingintion_hour,
first_ignition_on, last_ignition_off, cycle_count, average_cycle_distance_laden, first_cycle_start_timestamp, last_cycle_start_timestamp,
BCM_Total, tonnage_total, assest_group_caption, maintenance_hours, planned_maintenance_hours, uncontrollable_hours, total_idling_hours, availability_,
utilization_seconds,cycle_delay_seconds, known_operation_delay_seconds, other_travel_seconds, Unknown_operation_dealy_seconds)
SELECT DISTINCT
	replace(s.shift_caption,'-',''),
	s.shift_date,
	s.day_of_month,
	s.asset_caption,
	s.asset_class,
	cast(s.ignition_hour_start as FLOAT),
	CAST(s.ignition_hour_end AS FLOAT),
	CAST(s.total_ingintion_hour AS FLOAT),
	s.first_ignition_on,
	s.last_ignition_off,
	CAST(s.cycle_count AS INT),
	CAST(s.average_cycle_distance_laden AS FLOAT),
	s.first_cycle_start_timestamp,
	s.last_cycle_start_timestamp,
	CAST(s.BCM_Total AS FLOAT),
	CAST(s.tonnage_total AS INT),
	s.assest_group_caption,
	CAST(s.maintenance_hours AS FLOAT),
	CAST(s.planned_maintenance_hours AS INT),
	CAST(s.uncontrollable_hours AS FLOAT),
	CAST(s.total_idling_hours AS FLOAT),
	CAST(s.availability_ AS FLOAT),
	cast(s.utilization_seconds AS FLOAT),
	CAST(s.cycle_delay_seconds AS FLOAT),
	CAST(s.known_operation_delay_seconds AS FLOAT),
	CAST(s.other_travel_seconds AS FLOAT),
	CAST(s.Unknown_operation_dealy_seconds AS FLOAT) 	
FROM bronze.multi_shift s
WHERE s.asset_caption like 'Bell%';
SET @end_time = GETDATE();
PRINT '>>Load Duration: '+ CAST(DATEDIFF(SECOND, @start_time,@end_time) as NVARCHAR) + 'seconds';
PRINT '------------------------------------------------------------------------------------';
SET @start_time = GETDATE();
PRINT'>> Truncating Table: silver.cycle_review';
TRUNCATE TABLE silver.cycle_review;
PRINT '>> Inserting Data Into: silver.cycle_review';
INSERT INTO silver.cycle_review(start_timestamp, truck, shovel, material, loading_area, dumping_area, tonnage, fill_time, queue_time,cycle_time, travel_distance_laden_metres, average_speed_laden_km_h, 
	travel_seconds_laden, travel_distance_unladen_metres, average_speed_unladen_km_h, travel_seconds_unladen, dumping_time, 
	loading_time,dumping_timestamp, loading_timestamp, cycle_time_seconds)
SELECT DISTINCT
	c.start_timestamp,
	c.truck,
	c.shovel,
	c.material,
	c.loading_area,
	c.dumping_area,
	cast( c.tonnage as INT),
	CAST(c.fill_time as INT),
	CAST(c.queue_time as INT),
	CAST(c.cycle_time as INT),
	CAST(c.travel_distance_laden_metres AS INT),
	CAST(c.average_speed_laden_km_h AS FLOAT),
	CAST(c.travel_seconds_laden AS INT),
	CAST(c.travel_distance_unladen_metres AS INT),
	CAST(c.average_speed_unladen_km_h AS FLOAT),
	CAST(c.travel_seconds_unladen AS INT),
	CAST(c.dumping_time AS INT),
	CAST(c.loading_time AS INT),
	CAST(c.dumping_timestamp AS DATETIME),
	CAST( c.loading_timestamp AS DATETIME),
	CASE WHEN c.cycle_time_seconds = '#VALUE!' THEN ''
	else CAST(c.cycle_time_seconds AS INT)
	END cycle_time_seconds
FROM bronze.cycle_review c;
SET @end_time = GETDATE();
PRINT '>>Load Duration: '+ CAST(DATEDIFF(SECOND, @start_time,@end_time) as NVARCHAR) + 'seconds';
PRINT '------------------------------------------------------------------------------------';
SET @batch_end_time = GETDATE();
PRINT '===============================================================================';
PRINT 'Loading Silver Layer is Completed';
PRINT '	- Total Load Duration: ' + CAST( DATEDIFF(SECOND,@batch_start_time,@batch_end_time) as NVARCHAR)+'seconds';
PRINT '===============================================================================';
END TRY
	BEGIN CATCH
			PRINT '==============================================================================='
			PRINT 'ERROR OCCURED DURING LOADING Silver LAYER'
			PRINT 'ERROR MESSAGE' + ERROR_MESSAGE();
			PRINT 'ERROR MESSAGE' + CAST(ERROR_NUMBER() AS NVARCHAR);
			PRINT 'ERROR MESSAGE' + CAST(ERROR_STATE() AS NVARCHAR);

			PRINT '==============================================================================='
END CATCH 
END;
